logging:
  level: INFO
  loggers:
    "org.zenoss": DEBUG
performanceMetricQuery: 
  defaultExactTimeWindow: true
  defaultStartTime: 1h-ago
  defaultEndTime: now
  defaultSeries: false
  openTsdbUrl: http://tsdb.zenaas.com:4242
  defaultTsdTimeZone: UTC
  connectionTimeoutMs: 1000
http:
  connectorType: nonblocking
  port: 8888
  ssl:
      #Example is using a java keystore in the target directory.
      keyStore: ./target/ssl.pfx
      keyStorePassword: zapp_pass
      keyStoreType: pkcs12