logging:
  level: INFO
performanceMetricQuery: 
  defaultTimeZone: UTC
  defaultExactTimeWindow: true
  defaultStartTime: 1h-ago
  defaultEndTime: now
  openTsdbUrl: http://tsdb.zenaas.com:4242
http:
  connectorType: nonblocking
  port: 8888
  ssl:
      #Example is using a java keystore in the target directory.
      keyStore: ./target/ssl.pfx
      keyStorePassword: zapp_pass
      keyStoreType: pkcs12